!classDefinition: #Iann category: #ej1!
DenotativeObject subclass: #Iann
	instanceVariableNames: ''
	classVariableNames: ''
	poolDictionaries: ''
	category: 'ej1'!

"-- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- -- "!

!classDefinition: 'Iann class' category: #ej1!
Iann class
	instanceVariableNames: ''!

!Iann class methodsFor: '-- all --' stamp: 'i 3/13/2024 15:54:12'!
chau
	^'adios'! !

!Iann class methodsFor: '-- all --' stamp: 'i 3/13/2024 15:52:13'!
hola
	^'chau'! !
